config/routes.rb
Rails.application.routes.draw do
  root to: 'contacts#index'
  resources :contacts do
    post 'tag' => 'contacts#tag'
    resources :tags, only:[:new, :create]
  end

  post 'pages10' => 'contacts#pages10'
  post 'pages20' => 'contacts#pages20'
  post 'pages50' => 'contacts#pages50'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  has_many :tags, dependent: :destroy
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :contact
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  skip_before_action :authenticate_user!
  def index
    @contacts = Contact.all
    @pages = Page.first.number
  end

  def pages10
    Page.first.update(number: 10)
    redirect_to root_path
  end

  def pages20
    Page.first.update(number: 20)
    redirect_to root_path
  end

  def pages50
    Page.first.update(number: 50)
    redirect_to root_path
  end

  def show
    @contact = Contact.find(params[:id])
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)

    if @contact.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @contact = Contact.find(params[:id])
  end

  def update
    @contact = Contact.find(params[:id])
    if @contact.update(contact_params)
      redirect_to root_path, notice: 'modifié!'
    else
      render :edit
    end
  end

  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy
    redirect_to root_path
  end

  private

  def contact_params
    params.require(:contact).permit(:name)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  skip_before_action :authenticate_user!
  def new
    @contact = Contact.find(params[:contact_id])
    @tag = Tag.new
  end

  def create
    @contact = Contact.find(params[:contact_id])
    @tag = Tag.new(tag_params)
    @tag.contact = @contact
    if @tag.save
      redirect_to contact_path(@contact)
    else
      render :new
    end
  end

  private

  def tag_params
    params.require(:tag).permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/edit.html.erb
<h1>Edit contact</h1>
  <div class="row">
    <div class="col-sm-4 col-sm-offset-4">
      <div class="form-inputs">
        <%= simple_form_for [@contact] do |f| %>
        <%= f.input :name, label: 'Name' %>

        <%= f.button :submit, "Valider", class: "btn btn-primary" %>
      </div>
    </div>
</div>
  <% end %>

app/views/contacts/index.html.erb
<div class="container">
  <%= link_to 'créer un contact', new_contact_path, class: 'btn btn-warning m-4' %>
    <%= button_to '10', pages10_path, method: :post, class: "btn btn-success" %>
    <%= button_to '20', pages20_path, method: :post, class: "btn btn-success" %>
    <%= button_to '50', pages50_path, method: :post, class: "btn btn-success" %>
    <% @contacts.sort_by(&:created_at).reverse.first(@pages).each do |contact| %>
    <div class="card mb-4">
      <%= link_to contact_path(contact), class: "text-center" do %>
      <h2 class="text-center m-2"><%= contact.name %> <br>
        Tags:
        <% contact.tags.each do |tag| %>
          <%= tag.title %>
        <% end %>
      </h2>
      <% end %>
      <%= link_to 'Edit', edit_contact_path(contact), class: "btn btn-warning" %>
      <%= button_to "Destroy", contact, method: :delete, data: { confirm: "Êtes-vous sur?"} %>

    </div>
    <% end %>
</div>

app/views/contacts/new.html.erb
<h1>new contact</h1>
  <div class="row">
    <div class="col-sm-4 col-sm-offset-4">
      <div class="form-inputs">
        <%= simple_form_for [@contact] do |f| %>
        <%= f.input :name, label: 'Name' %>

        <%= f.button :submit, "Valider", class: "btn btn-primary" %>
      </div>
    </div>
</div>
  <% end %>

app/views/contacts/show.html.erb
<h2 class="text-center m-2"><%= @contact.name %></h2>
<h4> Tags:
  <% @contact.tags.each do |tag| %>
    <%= tag.title %>
  <% end %>
</h4>

<%= link_to 'Edit', edit_contact_path(@contact), class: "btn btn-warning" %>

<%= link_to 'créer un tag', new_contact_tag_path(@contact), class: "btn btn-warning" %>

<%= link_to 'Retour', contacts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EnginnTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/tags/new.html.erb
<div class="row">
  <div class="col-sm-4 col-sm-offset-4">
    <div class="form-inputs">
  <%= simple_form_for [@contact, @tag] do |f| %>
  <%= f.input :title, label: 'title' %>

  <%= f.button :submit, "Valider", class: "btn btn-primary" %>
   </div>
  </div>
</div>
  <% end %>